# generated by datamodel-codegen:
#   filename:  rollout.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class AlgorithmConfig1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['sft']
    learning_rate: float | None = Field(None, description='Learning rate override.')


class AlgorithmConfig2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ppo']
    kl_coef_init: float | None = Field(None, description='Initial KL coefficient.')


class AlgorithmConfig(RootModel[AlgorithmConfig1 | AlgorithmConfig2]):
    root: AlgorithmConfig1 | AlgorithmConfig2 = Field(
        ..., description='Algorithm selection.'
    )


class RunMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, description='Human-readable run name.')
    tags: list[str] | None = Field([], description='Free-form tags.')


class StorageConfig1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: Literal['embedded']
    path: str = Field(..., description='Filesystem path for the embedded DB.')


class StorageConfig2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: Literal['postgres']
    url: str = Field(..., description='Postgres connection URL.')


class StorageConfig(RootModel[StorageConfig1 | StorageConfig2]):
    root: StorageConfig1 | StorageConfig2 = Field(
        ..., description='Storage backend selection.'
    )


class RunConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: AlgorithmConfig = Field(..., description='Algorithm and its settings.')
    run: RunMetadata | None = Field(
        {'name': None, 'tags': []},
        description='Free-form metadata about the run.',
        validate_default=True,
    )
    schema_version: conint(ge=1, le=1) | None = Field(
        1, description='Schema version. v1 refuses configs with version > 1.'
    )
    storage: StorageConfig = Field(..., description='Storage backend selection.')
