//! `cargo xtask schema-gen` — regenerate JSON Schema + Python stubs + docs placeholder.
use rollout_core::config::RunConfig;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Run schema-gen. `args` are the CLI args after the subcommand name.
/// Supported flag: `--out-dir <PATH>` (default: workspace root inferred from cwd).
pub fn run(args: &[String]) -> i32 {
    let base = parse_out_dir(args).unwrap_or_else(workspace_root);
    let schema = schemars::schema_for!(RunConfig);
    let json = serde_json::to_string_pretty(&schema).expect("serialize schema");

    let schema_path = base.join("schemas/rollout.schema.json");
    if let Some(p) = schema_path.parent() {
        std::fs::create_dir_all(p).expect("mkdir schemas");
    }
    std::fs::write(&schema_path, format!("{json}\n")).expect("write schema");
    eprintln!("wrote {}", schema_path.display());

    let stubs_path = base.join("python/rollout/_config_stubs.py");
    if let Some(p) = stubs_path.parent() {
        std::fs::create_dir_all(p).expect("mkdir python/rollout");
    }

    if let Some(code) = run_datamodel_codegen(&schema_path, &stubs_path) {
        return code;
    }
    strip_codegen_timestamp(&stubs_path);
    eprintln!("wrote {}", stubs_path.display());

    let docs_path = base.join("docs/schema-reference.md");
    if let Some(p) = docs_path.parent() {
        std::fs::create_dir_all(p).expect("mkdir docs");
    }
    std::fs::write(
        &docs_path,
        "# Schema reference\n\n<!-- Generated by cargo xtask schema-gen. Do not edit. -->\n",
    )
    .expect("write docs");
    eprintln!("wrote {}", docs_path.display());

    0
}

/// Remove the `#   timestamp: ...` line datamodel-codegen embeds so the file is deterministic.
fn strip_codegen_timestamp(path: &Path) {
    let Ok(contents) = std::fs::read_to_string(path) else {
        return;
    };
    let cleaned: String = contents
        .lines()
        .filter(|l| !l.trim_start().starts_with("#   timestamp:"))
        .collect::<Vec<_>>()
        .join("\n");
    let mut out = cleaned;
    if !out.ends_with('\n') {
        out.push('\n');
    }
    std::fs::write(path, out).expect("rewrite stubs without timestamp");
}

fn run_datamodel_codegen(schema_path: &Path, stubs_path: &Path) -> Option<i32> {
    let status = Command::new("datamodel-codegen")
        .arg("--input")
        .arg(schema_path)
        .arg("--input-file-type")
        .arg("jsonschema")
        .arg("--output-model-type")
        .arg("pydantic_v2.BaseModel")
        .arg("--output")
        .arg(stubs_path)
        .status();
    match status {
        Ok(s) if s.success() => None,
        Ok(s) => {
            eprintln!("datamodel-codegen exited {s}");
            Some(2)
        }
        Err(e) => {
            eprintln!(
                "datamodel-codegen not found ({e}). Install: pip install datamodel-code-generator==0.57.0"
            );
            Some(2)
        }
    }
}

fn parse_out_dir(args: &[String]) -> Option<PathBuf> {
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--out-dir" {
            return it.next().map(PathBuf::from);
        }
        if let Some(rest) = a.strip_prefix("--out-dir=") {
            return Some(PathBuf::from(rest));
        }
    }
    None
}

fn workspace_root() -> PathBuf {
    std::env::current_dir().expect("cwd")
}
